module.exports={
	crypt:require("./crypt.js"),
	file:require("./file.js"),
	geo:require("./geo.js"),
	html:require("./html.js"),
	js:require("./js.js"),
	key_generator:require("./key_generator.js"),
	mongo:require("./mongo.js"),
	mysql:require("./mysql.js"),
	permissions:require("./permissions.js"),
	validation:require("./validation.js"),
}